### ISSUE TITLE
Remove the p tag

### ISSUE THREAD

**Issue by Drj-Ordonez** [nettejoe/IPT2-github#5]
Remove the p tag, so it will appear as one sentence.
![image](https://user-images.githubusercontent.com/111686144/197263724-b7a206da-05c7-44df-9fd7-89674149bd6d.png)

**Comment by JaysonWiilliams** [comment]
Sorry, didn't notice. Will work on it right away

**Comment by JaysonWiilliams** [comment]
already updated the file, done with the issue

**Comment by nettejoe** [comment]
Is this issue settled already?

**Comment by JaysonWiilliams** [comment]
Yep, it was settled together with the second issue

**Comment by nettejoe** [comment]
Okay, a big thank you. This matter is now resolved.
