### ISSUE TITLE
Text alignment and transform percent. 

### ISSUE THREAD

**Issue by Drj-Ordonez** [nettejoe/IPT2-github#6]
Add text-allign command on css file under class services-text p:nth-child 1,2,3 to make the center. Also, adjust the transform percent to uniform 100% to make the class services-text to make them move together simultaneously. 

![image](https://user-images.githubusercontent.com/111686144/197267708-bc640c71-08d2-4d8f-a5a8-422c718b9a3e.png)
![image](https://user-images.githubusercontent.com/111686144/197268221-ef27d569-149a-4770-a4c2-53447c4187d8.png)

**Comment by JaysonWiilliams** [comment]
alright, will resolve it right away.

**Comment by JaysonWiilliams** [comment]
resolved it already.

**Comment by nettejoe** [comment]
Is this issue already resolved?

**Comment by JaysonWiilliams** [comment]
it is already settled,try checking the code

**Comment by nettejoe** [comment]
The issue has been settled, and it will be closed.
